### ISSUE TITLE
Bad assignment of MotorStatus 

### ISSUE THREAD

**Issue by luisebt995** [RobotnikAutomation/robotnik_base_hw_sim#2]
In line 160-161:

ms.joint = self._motors[i]['joint']
ms.can_id = self._motors[i]['can_id']

The variable i is of type array and cannot be an index of itself

Possible Fix:

ms.joint = i['joint']
ms.can_id = i['can_id']

**Comment by RomanRobotnik** [comment]
Can you fix it, please? Thx

**Comment by luisebt995** [comment]
I need permission to publish a branch and create a pull request.
